name: crypto-nft-tweets-feature-and-prediction-pipelines

on:
  workflow_dispatch:
#  schedule:
#    - cron: '11 11 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - uses: 'actions/cache@v2'
        id: cache
        with:
          # CAUTION: Replace this hardcoded "python3.7" dirname with
          # the dirname providing your desired Python interpreter.
          path: ${{ env.pythonLocation }}/lib/python3.9/site-packages/*
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Install Jupyter
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install jupyter

      #- name: Check available kernels
       # run: jupyter kernelspec list
      
      #- name: Install or reconfigure python3 kernel
       # run: python -m ipykernel install --user --name python3 --display-name "Python 3"
          
      - name: Execute python scripts from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          X_RapidAPI_Key: ${{ secrets.X_RapidAPI_Key }}
          X_RapidAPI_Host: ${{ secrets.X_RapidAPI_Host }}
          url: ${{ secrets.url }}
        run: ./scripts/run-feature-and-prediction-pipelines.sh